### ISSUE TITLE
skip on duplicate key doesn't work

### ISSUE THREAD

**Issue by cmoroexpedia** [logstash-plugins/logstash-output-mongodb#10]
This piece of code doesn't seem to work (https://github.com/logstash-plugins/logstash-output-mongodb/blob/master/lib/logstash/outputs/mongodb.rb):

   if e.error_code == 11000
          # On a duplicate key error, skip the insert.
          # We could check if the duplicate key err is the _id key
          # and generate a new primary key.
          # If the duplicate key error is on another field, we have no way
          # to fix the issue.
      else

I have inserts failing due to duplicate key and it's sleeping and retrying instead of skipping the insert. I actually added some debug code and confirmed it's going into else statement:

if e.code == 11000
          @logger.warn("***************************\* ignored duplicate insert! ***************************_")
          # On a duplicate key error, skip the insert.
          # We could check if the duplicate key err is the _id key
          # and generate a new primary key.
          # If the duplicate key error is on another field, we have no way
          # to fix the issue.
      else
        @logger.warn("**_**************************\* will sleep and retry *********************************")
        sleep @retry_delay
        retry
      end

Results:
{:timestamp=>"2015-07-09T18:25:40.110000+0000", :message=>"Failed to send event to MongoDB", :event=>#<LogStash::Event:0x6a73dcc9 @accessors=#<LogStash::Util::Accessors:0x5ca446b8 @store={"ts"=>"2015-07-07T00:44:59.000Z", "label"=>"Flights-Search", "pos"=>"CHELWBTPRF-10.karmalab.net", "port"=>"55518", "server"=>"CHELWBTPRF-10", "status"=>"200", "size"=>"55836", "duration"=>453.113, "version"=>"trunk-trunk.ci.1406499", "_id"=>"89bd51974f7abb59622c3a537727331b_1277136"}, @lut={"@version"=>[{"ts"=>"2015-07-07T00:44:59.000Z", "label"=>"Flights-Search", "pos"=>"CHELWBTPRF-10.karmalab.net", "port"=>"55518", "server"=>"CHELWBTPRF-10", "status"=>"200", "size"=>"55836", "duration"=>453.113, "version"=>"trunk-trunk.ci.1406499", "_id"=>"89bd51974f7abb59622c3a537727331b_1277136"}, "@version"], "@timestamp"=>[{"ts"=>"2015-07-07T00:44:59.000Z", "label"=>"Flights-Search", "pos"=>"CHELWBTPRF-10.karmalab.net", "port"=>"55518", "server"=>"CHELWBTPRF-10", "status"=>"200", "size"=>"55836", "duration"=>453.113, "version"=>"trunk-trunk.ci.1406499", "_id"=>"89bd51974f7abb59622c3a537727331b_1277136"}, "@timestamp"], "[ts][$date]"=>[{"$date"=>"2015-07-07T00:44:59.000Z"}, "$date"], "ts"=>[{"ts"=>"2015-07-07T00:44:59.000Z", "label"=>"Flights-Search", "pos"=>"CHELWBTPRF-10.karmalab.net", "port"=>"55518", "server"=>"CHELWBTPRF-10", "status"=>"200", "size"=>"55836", "duration"=>453.113, "version"=>"trunk-trunk.ci.1406499", "_id"=>"89bd51974f7abb59622c3a537727331b_1277136"}, "ts"], "[label]"=>[{"ts"=>"2015-07-07T00:44:59.000Z", "label"=>"Flights-Search", "pos"=>"CHELWBTPRF-10.karmalab.net", "port"=>"55518", "server"=>"CHELWBTPRF-10", "status"=>"200", "size"=>"55836", "duration"=>453.113, "version"=>"trunk-trunk.ci.1406499", "_id"=>"89bd51974f7abb59622c3a537727331b_1277136"}, "label"]}>, @data={"ts"=>"2015-07-07T00:44:59.000Z", "label"=>"Flights-Search", "pos"=>"CHELWBTPRF-10.karmalab.net", "port"=>"55518", "server"=>"CHELWBTPRF-10", "status"=>"200", "size"=>"55836", "duration"=>453.113, "version"=>"trunk-trunk.ci.1406499", "_id"=>"89bd51974f7abb59622c3a537727331b_1277136"}, @cancelled=false>, :exception=>#<Mongo::OperationFailure: Database command 'insert' failed: (ok: '1'; n: '0'; writeErrors: '[{"index"=>0, "code"=>11000, "errmsg"=>"insertDocument :: caused by :: 11000 E11000 duplicate key error index: logstash.accessLogs.$_id_  dup key: { : \"89bd51974f7abb59622c3a537727331b_1277136\" }"}]').>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/mongo-1.10.2-java/lib/mongo/db.rb:576:in `command'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/mongo-1.10.2-java/lib/mongo/collection_writer.rb:314:in`send_write_command'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/mongo-1.10.2-java/lib/mongo/functional/logging.rb:55:in `instrument'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/mongo-1.10.2-java/lib/mongo/functional/logging.rb:20:in`instrument'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/mongo-1.10.2-java/lib/mongo/functional/logging.rb:54:in `instrument'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/mongo-1.10.2-java/lib/mongo/collection_writer.rb:313:in`send_write_command'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/mongo-1.10.2-java/lib/mongo/collection.rb:1076:in `send_write'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/mongo-1.10.2-java/lib/mongo/collection.rb:419:in`insert'", "/opt/logstash/lib/logstash/outputs/mongodb.rb:66:in `receive'", "/opt/logstash/lib/logstash/outputs/base.rb:86:in`handle'", "(eval):59:in `initialize'", "org/jruby/RubyProc.java:271:in`call'", "/opt/logstash/lib/logstash/pipeline.rb:266:in `output'", "/opt/logstash/lib/logstash/pipeline.rb:225:in`outputworker'", "/opt/logstash/lib/logstash/pipeline.rb:152:in `start_outputs'"], :level=>:warn}
{:timestamp=>"2015-07-09T18:25:40.112000+0000", :message=>"*****************************\* will sleep and retry *********************************", :level=>:warn}

**Comment by cmoroexpedia** [comment]
I fixed locally by changing that piece of code to:

```
 if e.message.include? "11000" 
      # On a duplicate key error, skip the insert.
      # We could check if the duplicate key err is the _id key
      # and generate a new primary key.
      # If the duplicate key error is on another field, we have no way
      # to fix the issue.
  else
    sleep @retry_delay
    retry
  end
```

not sure if it's the best option, but it works

**Comment by purbon** [comment]
@cmoroexpedia A fix introduced in the new release (https://rubygems.org/gems/logstash-output-mongodb) of this plugins should fix this issue by improving the check for duplicated error code. 

You can use the new plugin throw `bin/plugin update logstash-output-mongodb`  in logstash.

I will close this issue for now, feel free to reopen it in case you still see the issue.

Thanks for your contribution,
