### ISSUE TITLE
uninitialized constant Mongo::URIParser

### ISSUE THREAD

**Issue by crazw** [logstash-plugins/logstash-output-mongodb#15]
I also have this problem,does anybody can give me some suggests??
Thank you very much!

The version:

``` shell
Logstash:  V1.5.4
Mongodb: V 3.0.6
```

The conf file:

``` shell
output {
        mongodb {
                collection => "log_store"
                generateId => true
                database => "bigdata"

                uri => "mongodb://xxxx.com:27017"
       }
}
```

The error log:

``` shell
{:timestamp=>"2015-09-01T10:22:53.713000+0800", :message=>"The error reported is: \n  uninitialized constant Mongo::URIParser"}
{:timestamp=>"2015-09-01T10:32:22.014000+0800", :message=>"The error reported is: \n  uninitialized constant Mongo::URIParser"}
{:timestamp=>"2015-09-06T14:03:08.574000+0800", :message=>"The error reported is: \n  uninitialized constant Mongo::URIParser"}
```

**Comment by purbon** [comment]
I just release new version of this plugin (https://rubygems.org/gems/logstash-output-mongodb) with a fix that should get this issue disapeer. You can use the new plugin throw `bin/plugin update logstash-output-mongodb`  in logstash.

I will close this issue for now, feel free to reopen it in case you still see the issue.

Thanks for your contribution,
