### ISSUE TITLE
The version of mongodb output plugin present in logstash 1.4.2 doesn't support SCRAM-SHA-1 authentication mechanism for mongodb 3.0

### ISSUE THREAD

**Issue by svezzoli** [logstash-plugins/logstash-output-mongodb#2]
We use logstash 1.4.2 to store documents into MongoDB version 3.0 with new SCRAM-SHA-1 authentication mechanism enabled.

No documents are written in mongodb with following configuration file:
output {
mongodb {
collection => '%{type}'
database => 'nfmdata'
uri => 'mongodb://nfmoss:nfmoss@127.0.0.1'
}
}

If we add to uri parameter the connection authentication option:
uri => 'mongodb://nfmoss:nfmoss@127.0.0.1/?authMechanism=SCRAM-SHA-1'

we have the following error:
Mongo::MongoArgumentError: Invalid value "scram-sha-1" for authmechanism: must be one of GSSAPI, MONGODB-CR, MONGODB-X509, PLAIN

I think that mongodb output plugin has to be aligned to MongoDB Ruby driver 2.0.0 version, the only one version compatible with MongoDB version 3.0.
With the actual version of  MongoDB Ruby driver (1.10.2), the authentication toward MongoDB will fail because the server is expecting the driver to use the new SCRAM-SHA1 authentication protocol rather than the MONGODB-CR authentication protocol that it replaces.

It is possible to have this line up?
Thanks.

**Comment by svezzoli** [comment]
Any news?

**Comment by inptensib** [comment]
Hi i am facing the same problem.Is there any solution for this?I was thinking of upgrading the mongodb ruby driver but i am not very sure !!!

**Comment by svezzoli** [comment]
The support to keep working the logstash-output-mongodb plugin is it no more provided by github logstash-plugins community ?
I would like to know it, so I can search other solutions different from logstash.

**Comment by purbon** [comment]
@svezzoli As I told you in #3, please check for details https://github.com/logstash-plugins/logstash-output-mongodb/issues/3#issuecomment-136317157.

**Comment by purbon** [comment]
I close this one in benefit of #5 that is basically the same issue.
