### ISSUE TITLE
logstash-output-mongodb works only with mongodb 2.0.6

### ISSUE THREAD

**Issue by chakrip82** [logstash-plugins/logstash-output-mongodb#20]
Hi,
I tried to use logstash-output-mongodb and push to mongodb version 3.0.4 but its not working.
then i observed that its not working with mongodb 3.0.4 and throwing the error 

@metadata_accessors=#<LogStash::Util::Accessors:0x63ff2639 @store={}, @lut={}>, @cancelled=false>, :exception=>#<Mongo::Error::OperationFailure: assertion src/mongo/db/storage/mmap_v1/extent.h:77 (8)>, :backtrace=>["/Users/chakrapani.k/Downloads/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/mongo-2.0.6/lib/mongo/operation/result.rb:214:in `validate!'", "/Users/chakrapani.k/Downloads/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/mongo-2.0.6/lib/mongo/operation/write/insert.rb:72:in`execute_write_command'", "/Users/chakrapani.k/Downloads/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/mongo-2.0.6/lib/mongo/operation/write/insert.rb:62:in `execute'", "/Users/chakrapani.k/Downloads/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/mongo-2.0.6/lib/mongo/collection.rb:190:in`insert_many'", "/Users/chakrapani.k/Downloads/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/mongo-2.0.6/lib/mongo/collection.rb:175:in `insert_one'", "/Users/chakrapani.k/Downloads/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-output-mongodb-2.0.3/lib/logstash/outputs/mongodb.rb:56:in`receive'", "/Users/chakrapani.k/Downloads/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/outputs/base.rb:81:in `handle'", "(eval):27:in`output_func'", "/Users/chakrapani.k/Downloads/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:277:in `outputworker'", "/Users/chakrapani.k/Downloads/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:194:in`start_outputs'"], :level=>:warn}

Then i tried using this plugin with mongodb 2.0.6 and its working perfectly and able to push to mongodb.

Is there any workaround or fix for resolving this hard dependency on 2.0.6 and be able to push to mongo3 also.

regards,
chakri

**Comment by chakrip82** [comment]
the version of logstash which i used is logstash-2.1.1

**Comment by jjuarez** [comment]
It's not working with logstash 6.2.4 and MongoDB 3.4 too I could be wrong but it seems like a problem with the runtime gem dependency 2.0.6

**Comment by colinsurprenant** [comment]
relates to #42 and #35 to update driver.

**Comment by colinsurprenant** [comment]
Note that #59 was merged and version 3.1.6 has been published which now includes v2.6 of the driver.
This should solve here, free free to reopen if not.
