### ISSUE TITLE
enhancement - Change name of "@timestamp" field

### ISSUE THREAD

**Issue by cpiment** [logstash-plugins/logstash-output-mongodb#22]
First of all, I don't know if I have to register this here or if it is in other site. If I have opened this in the wrong place, can you redirect me to the place I should register it?

I'm using "logstash-output-mongodb" to avoid some process that I had to do on some CSV files, which I had to transform using a MongoDB Javascript function before loading the data in the collection. In that collection, the timestamp field is named "ts", but when the output filter inserts into the collection it names it "@timestamp"

Logstash doesn't support the change of name of "@timestamp" field, but would it be possible an enhancement that allows changing the name of the field before inserting it in MongoDB?

Thanks!

**Comment by cpiment** [comment]
I tested some changes in "mongodb.rb" and it seems to work:

https://github.com/cpiment/logstash-output-mongodb/blob/master/lib/logstash/outputs/mongodb.rb

**Comment by colinsurprenant** [comment]
This should not be required and you should be able to create a `ts` field using either the `mutate` filter and/or the `date` filter.

Closing, please feel free to reopen if needed.
