### ISSUE TITLE
Double quoted @timestamp field

### ISSUE THREAD

**Issue by Vitolog** [logstash-plugins/logstash-output-mongodb#24]
I'm using your logstash-output-mongodb plugin to send data to mongo database.
Below an example record stored in mongodb
`"@timestamp" : "\"2016-01-26T14:26:49.333Z\""`
As you can see, two double quotes are present  `"\".....\""`: this field isn't modified by my central.conf file.
I've tested my output with this code

```
output {
    mongodb {
      collection => "%{typelog}"
      database => "atest"
      uri => "mongodb://127.0.0.1/"
      codec => "json"
    }
   stdout { codec => rubydebug }
}
```

And this is what i obtain from stdout

```
{
           "@timestamp" => "2016-01-30T17:12:07.602Z",
     .....
}
```

This is my configuration

logstash 2.1.1
mongodb version v3.0.9

In stdout the double quotes problem is not present: what's wrong?
Thanks

**Comment by guyboertje** [comment]
@Vitolog - sincere apologies for the late reply.
The output that you see with the escaped quotes is the JSON string representation of the timestamp **as output** by Ruby not the internal record. All JSON strings and keys begin and end with a double quote. For example, see this representation of a JSON object having one string and one integer:
`{"key_str" : "a string", "key_int" : 42}` <-- this whole thing is a string. When Ruby **prints it out** it surrounds the whole thing with double quotes and escapes any internal double quotes. Inside MongoDB it is stored as `"a string"` not `"\"a string\""`

**Comment by kkbaranski** [comment]
@guyboertje no, inside MongoDB it is stored as `"\"a string\""` - I have the same problem. All fields are stored properly, only @timestamp appears with the escaped quotes. 

Example:

```
...

output {
  mongodb {
    collection => "some_collection"
    database => "test"
    uri => "mongodb://localhost"
  }
}
```

And mongodb console:

```
> db.some_collection.find().pretty()
{
  "_id" : ObjectId("58232d024188d1d5bd000001"),
  "@timestamp" : "\"2016-11-09T14:04:49.431Z\"",
  "host" : "127.0.0.1",
  "key1" : "value",
  "key2" : 100
}
> 
```

logstash 2.4.0
MongoDB shell version: 2.6.10

**Comment by kdcc** [comment]
come to the same problem..

**Comment by higee** [comment]
I've undergone same issue and my temporary solution is as follows.

```
input ...

filter {
  mutate {
    add_field => {"ts" => "%{@timestamp}"}
  }
  date {
    match => ["ts", "ISO8601"]
    target => "ts"
  }
}

output {
  mongodb {
    uri => ...
    database => ...
    collection => ...
  }
}
```

And `ts` field gets stored as ISODATE type in mongodb.

**Comment by senthil13** [comment]
+1 
I too have the same issue.
