### ISSUE TITLE
logstash-input-mongodb

### ISSUE THREAD

**Issue by Industrial** [logstash-plugins/logstash-output-mongodb#27]
Hi!

Just a small question: Why is there no input plugin for mongodb? Seems to be a very good fit?

There used to be a `river` thing but it's deprecated and now there is this `mongo-connector` but it's giving me errors about the oplog all the time and generally not working (yet).

**Comment by guyboertje** [comment]
@Industrial - Add an enhancement request to [Logstash issues](https://github.com/elastic/logstash/issues).
