### ISSUE TITLE
cannot install into logstash 5.x

### ISSUE THREAD

**Issue by lucidfrontier45** [logstash-plugins/logstash-output-mongodb#32]
- Version: logstash 5.1.1
- Operating System: ubuntu 16.04
- Steps to Reproduce: logstash-plugin install logstash-output-mongodb

Using `logstash-plugin` to install this plugin fails with lots of error messages

```
...
...
Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.1.1)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.1.1) java

    logstash-output-mongodb (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-output-mongodb (>= 0) java depends on
      logstash (< 2.0.0, >= 1.4.0) java
Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-output-mongodb (>= 0) java', in any of the sources.
```

Can you please build and upload a gem file that is compatible to Logstash 5.x?

**Comment by JaxWanCN** [comment]
I have same problem. :(

**Comment by JaxWanCN** [comment]
Can anybody  solve this problem?

**Comment by SuhasUnited90** [comment]
+1 Same problem any idea when this is planned to be solved ?

**Comment by sallyruthstruik** [comment]
+1 same problem

**Comment by kkbaranski** [comment]
+1

**Comment by jsvd** [comment]
[version 3.0.0](https://rubygems.org/gems/logstash-output-mongodb/versions/3.0.0) has been released, can you try it?

**Comment by patelparthiv** [comment]
+1. I tried the latest [version 3.1.0](https://rubygems.org/gems/logstash-output-mongodb/versions/3.1.0) with Logstash 5.2+ but it is not working.

**Comment by higee** [comment]
Logstash 6.1.0 didn't work either. 
Logstash 6.1.1, however, works properly.

**Comment by colinsurprenant** [comment]
I do not believe this is an issue anymore, closing. Please feel free to reopen if needed.
