### ISSUE TITLE
Is it possible to encrypt passwords for mongo uri connection string?

### ISSUE THREAD

**Issue by Ftwpker** [logstash-plugins/logstash-output-mongodb#34]
Have some requirements that logstash.conf file does not store the password to mongo in plaintext. Looked up some issues related to logstash but found they don't have a feature for it at this moment.

**Comment by colinsurprenant** [comment]
The secret keystore feature can be used. https://www.elastic.co/guide/en/logstash/current/keystore.html

Closing, please feel free to reopen if needed.
