### ISSUE TITLE
how can I specify username and password when using mongodb output plugin?

### ISSUE THREAD

**Issue by splf32** [logstash-plugins/logstash-output-mongodb#36]
This plugin doesn't have params like username or password. And I try to specify uri param like uri => "mongodb://username:password@host:port". But it can't work. Please tell me how to config it in logstash config file.

**Comment by reiz** [comment]
I'm asking myself the same question!

**Comment by reiz** [comment]
It would be `mongodb://username:password@localhost:27017`.

**Comment by reiz** [comment]
This can be closed.
