### ISSUE TITLE
The sync can't be stopped after date transfer over, It still cycle running.

### ISSUE THREAD

**Issue by mingyitianxia** [logstash-plugins/logstash-output-mongodb#40]
When I use the logstash-output-jdbc to sync date from elaticsearch V2.3.4 to mongodb V3.2.7, the plugin can't be stop immediately when the date end and the lines of date >= 10000.
The sync can't be stopped after date transfer over, It still cycle running from begin.
So I think it is a bug.
My logstash version is 2.3.4.

Thanks from your reply!

**Comment by colinsurprenant** [comment]
Sorry for not providing help on this - since this is quite old I will close this issue. Please feel free to reopen if you are still having problems with this.
