### ISSUE TITLE
Failed to send event to MongoDB ... ArgumentError: wrong number of arguments calling `initialize`

### ISSUE THREAD

**Issue by bakztfuture** [logstash-plugins/logstash-output-mongodb#43]
Hi everyone,

I have a basic logstash configuration which gets documents from elasticsearch, with no filter at all, and is supposed to insert them into mongodb in the output.

I keep getting this error repeatedly:
```
19:10:52.534 [[main]>worker2] WARN  logstash.outputs.mongodb - Failed to send event to MongoDB {:event=>2017-04-12T19:10:49.471Z %{host} %{message}, :exception=>#<ArgumentError: wrong number of arguments calling `initialize` (2 for 0)>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-mongodb-3.0.1/lib/logstash/outputs/mongodb.rb:54:in `receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:390:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:389:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:346:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:306:in `start_workers'"]}
^C19:10:54.473 [SIGINT handler] WARN  logstash.runner - SIGINT received. Shutting down the agent.
19:10:54.477 [LogStash::Runner] WARN  logstash.agent - stopping pipeline {:id=>"main"}

```

**Version:**
not sure, but the latest downloaded through logstash-plugin, running logstash 5.3

**Operating System:**
Ubuntu 16.10

**Config File (if you have sensitive info, please remove it):**
```
input {
  elasticsearch {
  hosts => ["*******","****", "***"]
  index => "******"
  # get the same error with or without a query
  user => "********"
  password => "**********"
  }
}
filter {}
output {
	mongodb {
		collection => "******"
		database => "*******"
		generateId => true
		uri => "*************"
	}
}
```
**Sample Data:**
I have a very basic elasticsearch document structure which has worked with other plugins in logstash ...

**Steps to Reproduce:**
Simply calling the configuration file returns this error

**Comment by bakztfuture** [comment]
had to drop generateID, and it was working, sorry for the mistake

**Comment by hjgCka** [comment]
This problem still exists today. And the document of logstash-output-mongodb hadn't been modified.

**Comment by saadlu** [comment]
> had to drop generateID, and it was working, sorry for the mistake

@bakztfuture why did you drop `generateId`?

My use case for using `generateId`: 

By default, id is an index (right?) I want to my logs to be indexed by id and `generatedId` will create Id based of timestamp.

Otherwise, I would need to create an additional index on `offset`.

Without index and sorting, my mongo client code is getting logs in unordered.
