### ISSUE TITLE
Logstash output getting failed with mongodb as output

### ISSUE THREAD

**Issue by mourya09** [logstash-plugins/logstash-output-mongodb#56]
Hi All,

I am trying to read multiple input json files and ingesting it into mongodb. 
Below is my LS conf file:
```
input{
file {
path => "D:/_sources/*.*"
start_position => "beginning"
type => "json"
sincedb_path=>"D:/sample.text"
}
}

output{
	mongodb {
		    id => "my_mongodb_plugin_id"
			collection => "configurations"
			database => "trueview"
			uri => "mongodb://localhost:27017/trueview"        
			codec => "json"
	}
}
```
and my input file is ss.json which is present under "D:/_sources/" folder.
```
{
    "GUID": "b92b650c-4f4a-438b-aa79-ca947329a9eb",
    "friendlyName":"supernova",
    "_type": "database",
    "_properties": {
        "auth":{
            "type": "Basic",
            "username": "admin",
            "password": "admin"
        },
        "_path": "http://localhost:8080",
        "serverMapsServiceSuffix":"/image.png"
    }
}
```
But it is not able to ingest anything in mongodb. Don't know what is wrong here with my inputs.

**Comment by colinsurprenant** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co/c/logstash. GitHub is for code issues and error reporting. Please make sure to include logs to help troubleshoot.

Feel free to reopen if you believe this should be looked at here. 

Thanks.
